name: CD - Deploy Production

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  deploy-prod:
    environment: production
    uses: ./.github/workflows/deploy_reusable.yml
    with:
      environment: production
      service_name: ${{ secrets.CLOUD_RUN_SERVICE_PROD }}
    secrets:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_REGION: ${{ secrets.GCP_REGION }}
      ARTIFACT_REPO: ${{ secrets.ARTIFACT_REPO }}
      GCP_WIF_PROVIDER: ${{ secrets.GCP_WIF_PROVIDER }}
      GCP_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
